version: "3"

services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/usr/src/app"
    tty: true
    stdin_open: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # db作成後にコンテナ作成
    depends_on:
      - db

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
