default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  template: template0

development:
  <<: *default
  database: bird_healthcare_backend_dev

test:
  <<: *default
  database: bird_healthcare_backend_test

production:
  <<: *default
  database: bird_healthcare_backend_prod
  # username: app
  # password: <%= ENV['APP_DATABASE_PASSWORD'] %>
